# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160225_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
    ]
