# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 02:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160316_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.IntegerField(default=0)),
                ('message', models.TextField(default=0)),
                ('public', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
                ('read_status', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[(b'text', b'Text'), (b'photo', b'Photo'), (b'video', b'Video')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drop',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drop',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
