# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160323_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='device_token',
        ),
        migrations.AddField(
            model_name='blockship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockship',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='blockships',
            field=models.ManyToManyField(related_name='blocked', through='api.Blockship', to=settings.AUTH_USER_MODEL),
        ),
    ]
