# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0002_auto_20160106_0850'),
        ('api', '0007_usercode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropDevice',
            fields=[
                ('apnsdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='push_notifications.APNSDevice')),
                ('badge', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('push_notifications.apnsdevice',),
        ),
    ]
