# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_dropdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_drops',
            field=models.BooleanField(default=True),
        ),
    ]
