# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160416_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='from_user_cleaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drop',
            name='to_user_cleaned',
            field=models.BooleanField(default=False),
        ),
    ]
