"""
Django settings for EmoTalk project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6q=+y#8vb)h81y#6_wb_s#!kkjd9!d_8sr@jweiaf57lw9f5r-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'api',
    'corsheaders',
    'django.contrib.sites',
    'rest_framework_docs',
    'push_notifications'
]

PUSH_NOTIFICATIONS_SETTINGS = {
    "APNS_CERTIFICATE": os.path.join(BASE_DIR, 'apns-dev-cert.pem'),
}
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DATETIME_FORMAT': "%Y-%m-%dT%H:%M:%S.%fZ",
}

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'EmoTalk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EmoTalk.wsgi.application'

AUTH_USER_MODEL = 'api.User'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, os.pardir, 'statics'))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.abspath(os.path.join(BASE_DIR, os.pardir, 'media'))

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR,  'templates'),
)

APPEND_SLASH = False

EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_HOST = 'email-smtp.us-east-1.amazonaws.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'AKIAIP3EKRIZWUCU54GQ'
EMAIL_HOST_PASSWORD = 'Albfat00OnnqvCKM5LWMV4YKxTbLmvqqBkoL6al8rHgk'
EMAIL_USE_TLS = True

DROP_EMOJI = [
    ':joy:',
    ':stuck_out_tongue_winking_eye:',
    ':wink:',
    ':smiley:',
    ':blush:',
    ':grin:',
    ':sunglasses:',
    ':relieved:',
    ':heart_eyes:',
    ':kissing_heart:',
    ':sob:',
    ':weary:',
    ':pensive:',
    ':smirk:',
    ':unamused:',
    ':disappointed_relieved:',
    ':flushed:',
    ':neutral_face:',
    ':sleeping:',
    ':relaxed:',
    ':heart:',
    ':broken_heart:',
    ':revolving_hearts:',
    ':cupid:',
    ':heartpulse:',
    ':sparkling_heart:',
    ':purple_heart:',
    ':two_hearts:',
    ':blue_heart:',
    ':kiss:',
    ':information_desk_person:',
    ':no_good:',
    ':dancer:',
    ':see_no_evil:',
    ':speak_no_evil:',
    ':monkey_face:',
    ':+1:',
    ':ok_hand:',
    ':wave:',
    ':clap:',
    ':raised_hands:',
    ':pray:',
    ':muscle:',
    ':point_up:',
    ':v:',
    ':fu:',
    ':hankey:',
    ':beers:',
    ':gift:',
    ':tada:',
    ':moneybag:',
    ':notes:',
    ':fire:',
    ':skull:',
    ':smiling_imp:',
    ':100:',
    ':thought_balloon:',
    ':sparkles:',
    ':eyes:',
    ':ghost:'
]
try:
    from local_settings import *
except:
    pass